
import { ProxyType, ProxySource } from './types';

// WARNING: These are public proxy lists. Quality and safety are not guaranteed. Use with caution.
// This list is a massive compilation from various public GitHub repositories and APIs.
// The total number of proxies from these sources can be in the hundreds of thousands.

export const PROXY_SOURCES: ProxySource[] = [
  // --- TXT Sources ---
  { url: 'https://raw.githubusercontent.com/rdavydov/proxies/main/proxies/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/aslisk/proxy-list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/proxy4parsing/proxy-list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/im-razvan/proxy_list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/official-proxy/proxies/main/http_proxies.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/proxy-list/fresh-proxy-list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies_anonymous/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/shiftytr/proxy-list/master/proxy.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/saisuiu/Lionkings-Http-Proxys-Proxies/main/free.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/caliphdev/Proxy-List/master/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/MuRongPIG/Proxy-Master/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/prxlist/proxy-list/main/http-ssl.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/proxylist-to/proxy-list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/prxlist/proxy-list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/official-proxy/proxies/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/HyperBeats/proxy-list/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_sources/http_proxies.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ProxyScraper/Proxy-List/main/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://openproxylist.xyz/http.txt', type: ProxyType.HTTP, format: 'txt' },
  { url: 'https://proxy-spider.com/api/proxies.example.txt', type: ProxyType.HTTP, format: 'txt' },

  { url: 'https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/official-proxy/proxies/main/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/prxlist/proxy-list/main/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/HyperBeats/proxy-list/main/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_sources/https_proxies.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/https.txt', type: ProxyType.HTTPS, format: 'txt' },
  
  { url: 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/prxlist/proxy-list/main/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/official-proxy/proxies/main/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_sources/socks4_proxies.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all', type: ProxyType.SOCKS4, format: 'txt' },
  { url: 'https://openproxylist.xyz/socks4.txt', type: ProxyType.SOCKS4, format: 'txt' },

  { url: 'https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/proxylist-to/proxy-list/main/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/prxlist/proxy-list/main/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/official-proxy/proxies/main/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/HyperBeats/proxy-list/main/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_sources/socks5_proxies.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/Zaeem20/FREE_PROXIES_LIST/master/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all', type: ProxyType.SOCKS5, format: 'txt' },
  { url: 'https://openproxylist.xyz/socks5.txt', type: ProxyType.SOCKS5, format: 'txt' },
  
  // --- JSON Sources ---
  { url: 'https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc', type: ProxyType.HTTP, format: 'json', jsonPath: 'data' },
  { url: 'https://api.proxyscrape.com/v3/free-proxy-list/get?request=displayproxies&protocol=http&proxy_format=ipport&format=json', type: ProxyType.HTTP, format: 'json', jsonPath: 'proxies' },
  { url: 'https://api.proxyscrape.com/v3/free-proxy-list/get?request=displayproxies&protocol=socks4&proxy_format=ipport&format=json', type: ProxyType.SOCKS4, format: 'json', jsonPath: 'proxies' },
  { url: 'https://api.proxyscrape.com/v3/free-proxy-list/get?request=displayproxies&protocol=socks5&proxy_format=ipport&format=json', type: ProxyType.SOCKS5, format: 'json', jsonPath: 'proxies' },
];